
import json
from pathlib import Path
from collections import defaultdict

ROOT = Path(__file__).resolve().parent.parent
JUDGE_PATH = ROOT / "results" / "judge_results.json"
OUTPUTS_PATH = ROOT / "results" / "rag_outputs.json"
REPORT_PATH = ROOT / "results" / "evaluation_report.md"

METRICS = [
    "correctness",
    "groundedness",
    "relevance",
    "abstention",
]


def load_json(path):
    with path.open("r", encoding="utf-8") as file:
        return json.load(file)


def average(values):
    return sum(values) / len(values) if values else None


def format_score(value):
    return f"{value:.2f}/5" if value is not None else "N/A"


def main():
    judgments = load_json(JUDGE_PATH)
    outputs = load_json(OUTPUTS_PATH)

    output_by_question = {
        item["question"]: item for item in outputs
    }

    grouped = defaultdict(list)
    metric_values = defaultdict(list)
    review_items = []

    for item in judgments:
        question = item["question"]
        original = output_by_question.get(question, {})
        category = item.get(
            "category", original.get("category", "unknown")
        )

        grouped[category].append(item)

        for metric in METRICS:
            score = item.get(metric)

            if isinstance(score, (int, float)) and 1 <= score <= 5:
                metric_values[metric].append(score)
            else:
                review_items.append(
                    f"Missing or invalid {metric} score: {question}"
                )

        scores = [
            item.get(metric)
            for metric in METRICS
        ]

        if any(
            not isinstance(score, (int, float))
            or not 1 <= score <= 5
            for score in scores
        ):
            continue

        # Flag low scores for human review.
        if any(score <= 2 for score in scores):
            review_items.append(
                f"Low evaluation score: {question}"
            )

        # Flag potentially contradictory judge explanations.
        reason = item.get("reason", "").lower()
        correctness = item["correctness"]

        if (
            correctness >= 4
            and "mostly incorrect" in reason
        ):
            review_items.append(
                f"Possible judge contradiction: {question}"
            )

    lines = [
        "# RAG Quality Lab — Evaluation Report",
        "",
        "## Overview",
        "",
        f"- Test cases generated: {len(outputs)}",
        f"- Cases evaluated by judge: {len(judgments)}",
        "- Generation model: Llama 3.2 via Ollama",
        "- Evaluation method: Llama-as-a-Judge",
        "",
        "## Overall Scores",
        "",
        "| Metric | Average Score |",
        "|---|---:|",
    ]

    for metric in METRICS:
        lines.append(
            f"| {metric.title()} | "
            f"{format_score(average(metric_values[metric]))} |"
        )

    lines += [
        "",
        "## Scores by Category",
        "",
        "| Category | Cases | Correctness | Groundedness | "
        "Relevance | Abstention |",
        "|---|---:|---:|---:|---:|---:|",
    ]

    for category, cases in sorted(grouped.items()):
        category_scores = {}

        for metric in METRICS:
            values = [
                case[metric]
                for case in cases
                if isinstance(case.get(metric), (int, float))
                and 1 <= case[metric] <= 5
            ]
            category_scores[metric] = average(values)

        lines.append(
            f"| {category} | {len(cases)} | "
            f"{format_score(category_scores['correctness'])} | "
            f"{format_score(category_scores['groundedness'])} | "
            f"{format_score(category_scores['relevance'])} | "
            f"{format_score(category_scores['abstention'])} |"
        )

    lines += [
        "",
        "## Individual Test Cases",
        "",
        "| Question | Category | Correctness | Groundedness | "
        "Relevance | Abstention |",
        "|---|---|---:|---:|---:|---:|",
    ]

    for item in judgments:
        question = item["question"].replace("|", "\\|")
        lines.append(
            f"| {question} | {item.get('category', 'unknown')} | "
            + " | ".join(
                format_score(item.get(metric))
                for metric in METRICS
            )
            + " |"
        )

    lines += [
        "",
        "## Items Requiring Review",
        "",
    ]

    if review_items:
        lines.extend(f"- {item}" for item in review_items)
    else:
        lines.append(
            "No automatically detected issues. "
            "Manual review is still required."
        )

    lines += [
        "",
        "## Limitations",
        "",
        "- Scores are generated by an LLM judge and may be inconsistent.",
        "- Automated flags are indicators for review, not proof of failure.",
        "- Retrieval quality must be assessed separately from answer quality.",
        "- Scores should be checked against human judgments before "
        "being treated as reliable performance measurements.",
        "",
    ]

    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text(
        "\n".join(lines), encoding="utf-8"
    )

    print("Evaluation report created:")
    print(REPORT_PATH)
    print(f"\nCases generated: {len(outputs)}")
    print(f"Cases judged: {len(judgments)}")
    print(f"Items flagged for review: {len(review_items)}")


if __name__ == "__main__":
    main()
